"""Generate a macOS Homebrew formula from the application wheel and uv.lock.

All dependency versions, download URLs and hashes come from the committed lock.
The generator performs no network requests.
"""

import argparse
import hashlib
import json
import tomllib
from pathlib import Path
from urllib.parse import unquote, urlparse

from packaging.markers import Marker, default_environment
from packaging.tags import compatible_tags, cpython_tags, mac_platforms
from packaging.utils import parse_wheel_filename


def resources(lock: dict, arch: str) -> list[tuple[str, dict]]:
    packages = {package["name"]: package for package in lock["package"]}
    environment = {
        **default_environment(),
        "sys_platform": "darwin",
        "os_name": "posix",
        "platform_machine": arch,
        "python_version": "3.14",
        "python_full_version": "3.14.0",
    }
    platforms = list(mac_platforms((14, 0), arch))
    supported = list(cpython_tags((3, 14), ["cp314"], platforms))
    supported += list(compatible_tags((3, 14), "cp314", platforms))
    ranks = {tag: index for index, tag in enumerate(supported)}
    selected = set()
    pending = [dependency["name"] for dependency in packages["cli-for-ynab"]["dependencies"]]
    while pending:
        name = pending.pop()
        if name in selected:
            continue
        selected.add(name)
        for dependency in packages[name].get("dependencies", []):
            if "marker" not in dependency or Marker(dependency["marker"]).evaluate(environment):
                pending.append(dependency["name"])
    result = []
    for name in sorted(selected):
        candidates = []
        for wheel in packages[name].get("wheels", []):
            filename = unquote(urlparse(wheel["url"]).path.rsplit("/", 1)[-1])
            tags = parse_wheel_filename(filename)[3]
            compatible = [ranks[tag] for tag in tags if tag in ranks]
            if compatible:
                candidates.append((min(compatible), wheel["url"], wheel))
        if not candidates:
            raise ValueError(f"No locked Python 3.14 macOS {arch} wheel for {name}")
        result.append((name, min(candidates, key=lambda row: row[:2])[2]))
    return result


def generate(wheel: Path, url: str, lock: dict) -> str:
    version = str(parse_wheel_filename(wheel.name)[1])
    if unquote(urlparse(url).path.rsplit("/", 1)[-1]) != wheel.name:
        raise ValueError("Release URL filename must match the built wheel")
    sha = hashlib.sha256(wheel.read_bytes()).hexdigest()
    arms = dict(resources(lock, "arm64"))
    intel = dict(resources(lock, "x86_64"))
    if arms.keys() != intel.keys():
        raise ValueError("Architecture-specific dependency sets need explicit handling")
    lines = [
        "# Generated by scripts/homebrew_formula.py; regenerate after dependency changes.",
        "class CliForYnab < Formula",
        "  include Language::Python::Virtualenv",
        "",
        '  desc "JSON CLI for YNAB budgets, categorization, targets, and spending reports"',
        '  homepage "https://github.com/dtour/cli-for-ynab"',
        f"  url {json.dumps(url)}, using: :nounzip",
        f"  version {json.dumps(version)}",
        f'  sha256 "{sha}"',
        '  license "MIT"',
        "",
        "  depends_on macos: :sonoma",
        '  depends_on "python@3.14"',
        "",
    ]
    for name, arm in arms.items():
        lines.append(f"  resource {json.dumps(name)} do")
        variants = (
            [(None, arm)]
            if arm["url"] == intel[name]["url"]
            else [("arm", arm), ("intel", intel[name])]
        )
        for arch, artifact in variants:
            indent = "      " if arch else "    "
            if arch:
                lines.append(f"    on_{arch} do")
            lines.append(f"{indent}url {json.dumps(artifact['url'])}, using: :nounzip")
            lines.append(f"{indent}sha256 {json.dumps(artifact['hash'].removeprefix('sha256:'))}")
            if arch:
                lines.append("    end")
        lines.extend(["  end", ""])
    lines.extend(
        [
            "  def install",
            '    venv = virtualenv_create(libexec, "python3.14", system_site_packages: false)',
            "    resources.each do |resource|",
            "      resource.stage do",
            '        venv.pip_install Dir["*.whl"]',
            "      end",
            "    end",
            f"    venv.pip_install_and_link buildpath/{json.dumps(wheel.name)}",
            "  end",
            "",
            "  test do",
            f'    assert_equal "{version}", shell_output("#{{bin}}/ynab --version").strip',
            '    assert_match "categorization automatically", shell_output("#{bin}/ynab guide")',
            '    catalog = JSON.parse(shell_output("#{bin}/ynab api list"))',
            '    assert_equal 44, catalog.dig("data", "count")',
            '    schema = shell_output("#{bin}/ynab api schema update_scheduled_transaction")',
            '    assert JSON.parse(schema).dig("data", "body_required")',
            '    ENV["YNAB_CONFIG_DIR"] = testpath/"config"',
            '    output = shell_output("#{bin}/ynab reports spending --month invalid 2>&1", 2)',
            '    assert_equal "invalid_month", JSON.parse(output).dig("error", "code")',
            "  end",
            "end",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wheel", required=True, type=Path)
    parser.add_argument("--url", required=True)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    lock = tomllib.loads(Path("uv.lock").read_text())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(args.wheel, args.url, lock))
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
